name: CI/CD

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js lts/*
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          check-latest: true
      - run: npm ci
      - run: npm run type-check
      - run: npm run coverage
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: ESLINT_USE_FLAT_CONFIG=false npm run lint
      - run: npm run dist
      - run: node ./scripts/generate-docs.js

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
